<?php

namespace VotacioBundle\Repository;

/**
 * PadroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PadroRepository extends \Doctrine\ORM\EntityRepository
{
}
