<?php

namespace VotacioBundle\Repository;

/**
 * QuestionariRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionariRepository extends \Doctrine\ORM\EntityRepository
{
}
